<x-tenant.customers.form
    :action="route('tenant.customers.update',$customer->no)"
    :districts="$districts"
    :counties="$counties"
    :idCustomer="$customer->id"
    :name="$customer->name"
    :surname="$customer->surname"
    :slug="$customer->slug"
    :vat="$customer->nif"
    :email="$customer->email"
    :contact="$customer->phone"
    :address="$customer->address"
    :username="$customer->username"
    :zipcode="$customer->zipcode"
    :district="$customer->state"
    :county="$customer->city"
    :update="true" buttonAction="Atualizar Cliente"
    formTitle="Atualizar Cliente"/>
